### ISSUE TITLE
Parser support for 3.0 and 3.1

### ISSUE THREAD

**Issue by fgsch** [fzipi/secrules-parser#2]
I've opened #1 to fix some issues with v3.1/dev.

Should I add support for v3.0/dev as well? 
Do we want to support both versions in a single metamodel?

Let me know what your thoughts are and I can modify it to handle both.

**Comment by fzipi** [comment]
Hi @fgsch, thanks for patch #1!

Do you think it is relevant to add support for v3.0/dev? It it is for you, just do it.

I will begin working on using the parser for converting rules to the 'CRS format' of the new 3.1/dev. I've got a lot of rules written that will benefit from this.

**Comment by fgsch** [comment]
While I'm still using 3.0 I think we should focus on 3.1, so either have different metamodels for each version, or drop 3.0 entirely.

That said, in order to parse the Trustwave ruleset more work is needed (I have part of this done already) and I think they are closer to 3.0 than 3.1.

So perhaps the best course of action is to have a single metamodel that supports everything and once that's done figure the next steps. This might make more sense in context of #4 as well.

**Comment by fzipi** [comment]
I agree. Sadly, as I don't have the Trustvawe ruleset here, I would delegate that task on you. When/If I put my hands on it, I can help you with that.

**Comment by fgsch** [comment]
I have one outstanding change to fix parsing in v3.1/dev (related to https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1017).

I will try to open it this week before moving to Trustwave.

**Comment by fgsch** [comment]
Remaining work for v3.1/dev support at https://github.com/fzipi/secrules-parser/pull/6.

**Comment by fgsch** [comment]
This should be completed now.
